### ISSUE TITLE
Variable dg not defined, cant make google analytics module work

### ISSUE THREAD

**Issue by x7ian** [signalpoint/google_analytics#1]
Sorry but i cant make this work. 
Follow the instructions but it seems like the dg variable is not defined anywhere. And thats how the doc says it must be configured, using dg.settings... and also at the module it uses dg.modules.google_analytics... however it gives an error that the variable dg is not defined.
I tried changing the variable to "drupalgap" wich is the variable used all over the settings file. However the methods used in the module are not defined anywhere eigther.
Defining dg.settings.google_analytics at settings.js makes no sense since there is no previows definition of 'dg' variable.
Then when includding the module, it gives the same error again cause the variable dg is not defined and the module defines a new object of class dg.Module(), again the dg variable is not defined.
Finally when adding the GA code it to the index.html gives the same error again since it is calling the method .config with is not defined anywhere.

Any ideas of what can i be missing?
Have tou guys actually made this work with the current instructions?

**Comment by signalpoint** [comment]
@x7ian The `dg` variable is only for DrupalGap 8, and this module is only available for DrupalGap 8.

It sounds like you are trying to use this DrupalGap 8 module with the DrupalGap 7 SDK.

Please verify you've downloaded DrupalGap 8 (which is not the default branch): https://github.com/signalpoint/drupalgap/tree/8.x-1.x

**Comment by signalpoint** [comment]
@x7ian I stand corrected, there is also a DrupalGap 7 version of this module: https://github.com/signalpoint/google_analytics/tree/7.x-1.x

Just make sure to grab either the 7 or 8 version, depending on what version of Drupal/DrupalGap you are using.

**Comment by x7ian** [comment]
Oh gosh! Im using D7,
Sorry for the "issue"! My awful mistake!
And thank you again @signalpoint, for saving my and many peoples days! :-D

**Comment by signalpoint** [comment]
@x7ian No problem, thank you for following up.
